function workflow = GetWorkflow()

% workflow = {
%     'ModuleLoadImage', ...
%     'ModuleTransformImage', ...
%     'ModuleDetectNuclei', ...
%     'ModuleCorrectErrors', ...
%     'ModuleSegmentNuclei', ...
%     'ModuleExportResults'};


workflow = {
    'ModuleLoadImage', ...
    'ModuleTransformImage', ...
    'ModuleDetectNuclei', ...
    'ModuleSegmentNuclei', ...
    'ModuleClassifyNuclei', ...
    'ModuleExportResults'};

% workflow = {
%     'ModuleLoadImage', ...
%     'ModuleTransformImage', ...
%     'ModuleDetectNuclei', ...
%     'ModuleClassifyNuclei', ...
%     'ModuleExportResults'};
